<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql
select *
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [3]:
%%sql
select *,
  orderdate,
  customerkey,
  quantity * netprice as net_revenue
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate,orderdate,customerkey,net_revenue
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64,2015-01-01,947009,98.97
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64,2015-01-01,947009,659.78
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00,2015-01-01,1772036,108.75
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00,2015-01-01,1518349,1146.75
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00,2015-01-01,1518349,950.25
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00,2015-01-01,1518349,1302.91
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00,2015-01-01,1518349,58.73
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00,2015-01-01,1317097,224.98
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16,2015-01-01,254117,227.15
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16,2015-01-01,254117,499.45

In [4]:
%%sql
select
  orderdate,
  customerkey,
  quantity * netprice * exchangerate as net_revenue
from sales
where orderdate >= '2020-01-01'
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  customerkey  net_revenue
0  2020-01-01       593517        99.47
1  2020-01-01       593517       139.97
2  2020-01-01       593517       669.39
3  2020-01-01       593517      4090.60
4  2020-01-01       307502       237.15
5  2020-01-01      1413265      1507.16
6  2020-01-01      1413265       189.35
7  2020-01-01      1413265       539.90
8  2020-01-01      1567083      5590.00
9  2020-01-01      1855428      3580.00

In [5]:
%%sql
select
  sal.orderdate,
  cust.surname,
  cust.givenname,
  cust.middleinitial,
  sal.customerkey,
  sal.quantity * netprice as net_revenue
from sales sal
inner join customer cust
on sal.customerkey = cust.customerkey
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  surname givenname middleinitial  customerkey  net_revenue
0  2015-01-01     Rowe    Hayden             B       947009        98.97
1  2015-01-01     Rowe    Hayden             B       947009       659.78
2  2015-01-01   Tejeda   Beverly             B      1772036       108.75
3  2015-01-01   Daniel    Kristi             B      1518349      1146.75
4  2015-01-01   Daniel    Kristi             B      1518349       950.25
5  2015-01-01   Daniel    Kristi             B      1518349      1302.91
6  2015-01-01   Daniel    Kristi             B      1518349        58.73
7  2015-01-01  Holland   Richard             C      1317097       224.98
8  2015-01-01    Gabor      Jack             A       254117       227.15
9  2015-01-01    Gabor      Jack             A       254117       499.45

In [6]:
%%sql
select
  sal.customerkey,
  sal.orderdate,
  prod.productname,
  cust.surname,
  cust.givenname,
  cust.countryfull,
  cust.continent,
  sal.quantity * netprice as net_revenue,
case
  when netprice * quantity <= 1000 then 'Low'
  when netprice* quantity > 1000 then 'High'
  end as revenue_category
from sales sal
left join customer cust
on sal.customerkey = cust.customerkey
left join product prod
on sal.productkey = prod.productkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderdate,productname,surname,givenname,countryfull,continent,net_revenue,revenue_category
0,737310,2015-01-07,NT Wireless Bluetooth Stereo Headphones E302 B...,Lorenzo,Angela,Italy,Europe,55.96,Low
1,363407,2015-01-07,Contoso Rechargeable Battery Pack E310 White,Perine,Melissa,Canada,North America,100.79,Low
2,363407,2015-01-07,WWI Stereo Bluetooth Headphones E1000 White,Perine,Melissa,Canada,North America,224.95,Low
3,363407,2015-01-07,MGS Hand Games for kids E300 Black,Perine,Melissa,Canada,North America,10.16,Low
4,591707,2015-01-08,Contoso DVD 48 DVD Storage Binder M50 Silver,Möller,Tobias,Germany,Europe,10.79,Low
...,...,...,...,...,...,...,...,...,...
199868,268983,2024-04-18,Proseware LCD20 M200 White,Ammons,Alfreda,Canada,North America,932.40,Low
199869,268983,2024-04-18,Contoso Conversion Lens M550 Blue,Ammons,Alfreda,Canada,North America,547.35,Low
199870,1263482,2024-04-19,Contoso Expandable 4-Handset Cordless Phone Sy...,Cook,Elsie,United States,North America,87.62,Low
199871,1263482,2024-04-19,SV DVD 9-Inch Player Portable M300 White,Cook,Elsie,United States,North America,563.16,Low
199872,1263482,2024-04-19,WWI Desktop PC1.80 E1801 Brown,Cook,Elsie,United States,North America,2159.20,High

In [7]:
## COUNT DISTINCT

%%sql
SELECT
  sal.orderdate,
  count(distinct case when cust.continent = 'Europe' then sal.customerkey end) as eu_customers,
  count(distinct case when cust.continent = 'North America' then sal.customerkey end) as na_customers,
  count(distinct case when cust.continent = 'Australia' then sal.customerkey end) as aus_customers
from sales sal
left join customer cust
on sal.customerkey = cust.customerkey
where sal.orderdate between '2023-01-01' and '2023-12-31'
group by sal.orderdate
order by sal.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  eu_customers  na_customers  aus_customers
0    2023-01-01             6             5              1
1    2023-01-02            15            31              3
2    2023-01-03            17            44              3
3    2023-01-04            28            46              4
4    2023-01-05            22            57              8
..          ...           ...           ...            ...
359  2023-12-27            26            41              6
360  2023-12-28            24            44              7
361  2023-12-29            19            32              4
362  2023-12-30            25            50             16
363  2023-12-31             1             8              0

[364 rows x 4 columns]

In [8]:
## sum with case

%%sql
SELECT
  prod.categoryname,
  sum(case when sal.orderdate between '2022-01-01' and '2022-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) net_revenue_2022,
  sum(case when sal.orderdate between '2023-01-01' and '2023-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) net_revenue_2023,
  sum(case when sal.orderdate between '2024-01-01' and '2024-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) net_revenue_2024
from sales sal
left join product prod
on sal.productkey = prod.productkey
group by prod.categoryname
order by prod.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,net_revenue_2022,net_revenue_2023,net_revenue_2024
0,Audio,766938.21,688690.18,209228.64
1,Cameras and camcorders,2382532.56,1983546.29,635084.71
2,Cell phones,8119665.07,6002147.63,1685744.55
3,Computers,17862213.49,11650867.21,2957039.62
4,Games and Toys,316127.30,270374.96,85867.75
5,Home Appliances,6612446.68,5919992.87,1320161.48
6,"Music, Movies and Audio Books",2989297.28,2180768.13,592662.15
7,TV and Video,5815336.61,4412178.23,910738.50

In [9]:
%%sql
select*
from product

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2517 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2513,505026,Contoso Bluetooth Active Headphones L15 Red,"Contoso, Ltd",Contoso,Red,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2513,2514,505027,Contoso Bluetooth Active Headphones L15 White,"Contoso, Ltd",Contoso,White,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2514,2515,505028,Contoso In-Line Coupler E180 White,"Contoso, Ltd",Contoso,White,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2515,2516,505029,Contoso In-Line Coupler E180 Black,"Contoso, Ltd",Contoso,Black,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2516,2517,505030,Contoso In-Line Coupler E180 Silver,"Contoso, Ltd",Contoso,Silver,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories

In [10]:
## STATISTICS (MAX, MIN, MEAN, AVG, MEDIAN)
## AVG
%%sql
SELECT
  prod.categoryname,
  MAX(case when sal.orderdate between '2022-01-01' and '2022-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) max_revenue_2022,
  MAX(case when sal.orderdate between '2023-01-01' and '2023-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) max_revenue_2023,
  min(case when sal.orderdate between '2022-01-01' and '2022-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) min_revenue_2022,
  min(case when sal.orderdate between '2023-01-01' and '2023-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) min_revenue_2023,
  avg(case when sal.orderdate between '2022-01-01' and '2022-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) net_avg_revenue_2022,
  avg(case when sal.orderdate between '2023-01-01' and '2023-12-31' then sal.quantity * sal.netprice * sal.exchangerate end) net_avg_revenue_2023
from sales sal
left join product prod
on sal.productkey = prod.productkey
group by prod.categoryname
order by prod.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,max_revenue_2022,max_revenue_2023,min_revenue_2022,min_revenue_2023,net_avg_revenue_2022,net_avg_revenue_2023
0,Audio,3473.36,2730.87,9.31,10.85,392.30,425.38
1,Cameras and camcorders,15008.39,13572.00,6.74,5.98,1210.02,1210.96
2,Cell phones,7692.37,8912.22,2.53,2.28,722.20,623.28
3,Computers,38082.66,27611.60,0.83,0.75,1565.62,1292.39
4,Games and Toys,5202.01,3357.30,2.83,3.49,81.29,80.83
5,Home Appliances,31654.55,32915.59,4.04,4.54,1755.36,1886.55
6,"Music, Movies and Audio Books",5415.19,3804.91,7.29,6.91,386.61,334.58
7,TV and Video,30259.41,27503.12,41.30,42.30,1535.61,1687.90

In [11]:
## median
%%sql
select
  PERCENTILE_CONT(0.5) within group (order by netprice) as median_price
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [12]:
## MEDIAN

%%sql
SELECT
  prod.categoryname as category,
  PERCENTILE_CONT(0.5) within group (order by
  ( case
    when orderdate between '2022-01-01' and '2022-12-01' then (sal.quantity*sal.netprice*sal.exchangerate) end)) as  median_revenue_2022,
     PERCENTILE_CONT(0.5) within group (order by
  ( case
    when orderdate between '2023-01-01' and '2023-12-01' then (sal.quantity*sal.netprice*sal.exchangerate) end)) as  median_revenue_2023
from sales sal
left join product prod
on sal.productkey = prod.productkey
group by prod.categoryname
order by prod.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  median_revenue_2022  median_revenue_2023
0                          Audio               256.51               265.98
1        Cameras and camcorders                656.00               676.00
2                    Cell phones               421.40               369.79
3                      Computers               823.46               657.35
4                 Games and Toys                33.98                32.62
5                Home Appliances               789.75               827.75
6  Music, Movies and Audio Books               189.27               158.39
7                   TV and Video               724.99               782.88

In [13]:
%%sql
select
  orderdate,
  quantity,
  netprice,
case
  WHEN quantity >= 2 and netprice >= 100 then 'Multiple High Value Order'
  when netprice >= 100 then 'Single High Value Order'
  WHEN quantity >= 2 then 'Multiple Standard Item'
  else 'Single Standard item'
  end as order_type
from sales

limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97       Single Standard item
1  2015-01-01         1    659.78    Single High Value Order
2  2015-01-01         2     54.38     Multiple Standard Item
3  2015-01-01         4    286.69  Multiple High Value Order
4  2015-01-01         7    135.75  Multiple High Value Order
5  2015-01-01         3    434.30  Multiple High Value Order
6  2015-01-01         1     58.73       Single Standard item
7  2015-01-01         3     74.99     Multiple Standard Item
8  2015-01-01         2    113.57  Multiple High Value Order
9  2015-01-01         1    499.45    Single High Value Order

In [14]:
%%sql
select
  PERCENTILE_CONT(0.5) within group (order by quantity*netprice*exchangerate) as median_revenue_2022
from sales
where orderdate between '2022-01-01' and '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_revenue_2022
0               398.00

In [15]:
%%sql
SELECT
  prod.categoryname as category,
  sum(case when (sal.quantity*sal.netprice*sal.exchangerate) < 398
      and sal.orderdate between  '2022-01-01' and '2022-12-31'
    then (sal.quantity*sal.netprice*sal.exchangerate) end ) as low_net_revenue_2022,
  sum(case when (sal.quantity*sal.netprice*sal.exchangerate) >= 398
       and sal.orderdate between  '2022-01-01' and '2022-12-31'
   then (sal.quantity*sal.netprice*sal.exchangerate) end ) as high_net_revenue_2022,
     sum(case when (sal.quantity*sal.netprice*sal.exchangerate) < 398
      and sal.orderdate between  '2023-01-01' and '2023-12-31'
    then (sal.quantity*sal.netprice*sal.exchangerate) end ) as low_net_revenue_2022,
  sum(case when (sal.quantity*sal.netprice*sal.exchangerate) >+ 398
       and sal.orderdate between  '2023-01-01' and '2023-12-31'
   then (sal.quantity*sal.netprice*sal.exchangerate) end ) as high_net_revenue_2022
from sales sal
left join product prod
on sal.productkey = prod.productkey
group by prod.categoryname
order by prod.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2022,high_net_revenue_2022
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5266478.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4246708.87

In [ ]:
%%sql
with percentiles as
(
SELECT

  PERCENTILE_CONT(0.25) within group (order by (sal.quantity * sal.netprice * sal.exchangerate)) as revenue_25th_percentile ,
  PERCENTILE_CONT(0.50) within group (order by (sal.quantity * sal.netprice * sal.exchangerate)) as revenue_50th_percentile ,
  PERCENTILE_CONT(0.75) within group (order by (sal.quantity * sal.netprice * sal.exchangerate)) as revenue_75th_percentile
from sales sal
where orderdate between '2022-01-01' and '2023-12-31'
)
select
 prod.categoryname as category,
 case
     when (sal.quantity * sal.netprice * sal.exchangerate) <= perc.revenue_25th_percentile then 'low'
     when (sal.quantity * sal.netprice * sal.exchangerate) >= perc.revenue_50th_percentile then 'middium'
     else 'high'
     end as revenue_category  ,
sum(sal.quantity * sal.netprice * sal.exchangerate) as net_revenue
from sales sal
left join product prod
on sal.productkey = prod.productkey,
percentiles perc
group by prod.categoryname,
         revenue_category
order by prod.categoryname